-- Create table if it doesn't exist (Safe for Dev Mode)
CREATE TABLE IF NOT EXISTS "exercise" (
                                          "exercise_id" INTEGER PRIMARY KEY,
                                          "name" VARCHAR(255) NOT NULL,
                                          "description" TEXT
);

-- Fast Transactional Insert
BEGIN;

-- Clear table prevents ID conflicts if you run this script multiple times
TRUNCATE TABLE "exercise" RESTART IDENTITY;

INSERT INTO "exercise" ("exercise_id", "name", "description") VALUES
-- CHEST
(1, 'Barbell Bench Press', 'A compound exercise that targets the chest, shoulders, and triceps. Lie on a flat bench and press the weight upward.'),
(2, 'Incline Barbell Bench Press', 'Similar to the flat bench press but performed on an incline to target the upper chest.'),
(3, 'Decline Barbell Bench Press', 'Performed on a decline bench to target the lower pectorals.'),
(4, 'Dumbbell Bench Press', 'Chest press performed with dumbbells, allowing for a greater range of motion.'),
(5, 'Incline Dumbbell Press', 'Dumbbell press on an incline bench for upper chest development.'),
(6, 'Dumbbell Flyes', 'An isolation movement for the chest using dumbbells on a flat bench.'),
(7, 'Incline Dumbbell Flyes', 'Isolation movement for the upper chest using dumbbells.'),
(8, 'Cable Crossover', 'Standing isolation exercise using high pulleys to target the inner chest.'),
(9, 'Low Cable Crossover', 'Standing isolation exercise pulling from low to high to target upper chest.'),
(10, 'Pec Deck Machine', 'Machine-based fly movement to isolate pectoral muscles.'),
(11, 'Chest Press Machine', 'Seated machine press for safe, controlled chest training.'),
(12, 'Push-Up', 'Classic bodyweight exercise targeting chest, shoulders, and core.'),
(13, 'Diamond Push-Up', 'Push-up variation with hands close together to target triceps and inner chest.'),
(14, 'Weighted Push-Up', 'Push-ups performed with a plate on the back or a weighted vest.'),
(15, 'Wide Grip Push-Up', 'Push-ups with hands placed wider than shoulder-width to emphasize the chest.'),
(16, 'Decline Push-Up', 'Feet elevated push-up to target the upper chest and shoulders.'),
(17, 'Dips (Chest Focus)', 'Bodyweight dip leaning forward to emphasize pectorals over triceps.'),
(18, 'Svend Press', 'Isometric chest exercise pressing two plates together in front of the chest.'),
(19, 'Landmine Press', 'Pressing a barbell anchored at one end, targeting upper chest and shoulders.'),
(20, 'Floor Press', 'Bench press variation performed lying on the floor to limit range of motion.'),

-- BACK
(21, 'Deadlift (Conventional)', 'Compound lift targeting the entire posterior chain, specifically lower back, glutes, and hamstrings.'),
(22, 'Sumo Deadlift', 'Deadlift variation with a wide stance, shifting focus to hips and quads.'),
(23, 'Pull-Up', 'Bodyweight vertical pull targeting the lats and biceps with palms facing away.'),
(24, 'Chin-Up', 'Bodyweight vertical pull with palms facing you, emphasizing biceps and lats.'),
(25, 'Lat Pulldown', 'Machine vertical pull mimicking the pull-up pattern.'),
(26, 'Wide Grip Lat Pulldown', 'Lat pulldown with a wide grip to emphasize lat width.'),
(27, 'Bent Over Barbell Row', 'Compound horizontal pull targeting the middle back and lats.'),
(28, 'Pendlay Row', 'Barbell row where the weight settles on the floor between every rep.'),
(29, 'Single Arm Dumbbell Row', 'Unilateral rowing movement supported by a bench.'),
(30, 'Seated Cable Row', 'Horizontal rowing movement using a cable machine.'),
(31, 'T-Bar Row', 'Rowing movement using a T-Bar machine or landmine setup.'),
(32, 'Chest Supported Row', 'Machine or dumbbell row lying face down on an incline bench to prevent cheating.'),
(33, 'Face Pull', 'Cable exercise pulling towards the face to target rear delts and rotator cuff.'),
(34, 'Straight Arm Pulldown', 'Isolation exercise for the lats using a cable machine.'),
(35, 'Dumbbell Pullover', 'Exercise stretching the lats and chest, performed lying on a bench.'),
(36, 'Back Extension', 'Exercise targeting the lower back using a hyperextension bench.'),
(37, 'Good Morning', 'Hinging movement with a barbell on the shoulders targeting hamstrings and lower back.'),
(38, 'Rack Pull', 'Partial deadlift starting from rack pins to target the upper back and lockout.'),
(39, 'Inverted Row', 'Bodyweight row performed hanging under a bar (Australian Pull-up).'),
(40, 'Meadows Row', 'Unilateral landmine row variation promoting a deep stretch.'),

-- SHOULDERS
(41, 'Overhead Press (Military Press)', 'Standing barbell press targeting the entire shoulder girdle.'),
(42, 'Seated Dumbbell Press', 'Shoulder press performed seated with dumbbells.'),
(43, 'Arnold Press', 'Dumbbell press with a rotation component, hitting all three deltoid heads.'),
(44, 'Push Press', 'Overhead press utilizing a leg drive to move heavier weights.'),
(45, 'Lateral Raise', 'Isolation exercise raising dumbbells to the side for medial deltoids.'),
(46, 'Front Raise', 'Raising weights forward to target the anterior deltoid.'),
(47, 'Rear Delt Fly (Dumbbell)', 'Bent-over fly movement targeting the posterior deltoid.'),
(48, 'Reverse Pec Deck', 'Machine fly utilizing the rear deltoids.'),
(49, 'Upright Row', 'Pulling weight vertically up the body to target traps and side delts.'),
(50, 'Shrugs (Barbell)', 'Lifting shoulders towards ears to target the upper trapezius.'),
(51, 'Shrugs (Dumbbell)', 'Shrugs performed with dumbbells at the sides.'),
(52, 'Cable Lateral Raise', 'Lateral raise using a low pulley for constant tension.'),
(53, 'Egyptian Lateral Raise', 'Leaning cable lateral raise for better stretch on the medial delt.'),
(54, 'Behind The Neck Press', 'Barbell press lowered behind the head (requires good mobility).'),
(55, 'Landmine Shoulder Press', 'Unilateral pressing movement using a landmine anchor.'),

-- LEGS (QUADS & GLUTES)
(56, 'Barbell Back Squat', 'The king of leg exercises targeting quads, glutes, and core.'),
(57, 'Front Squat', 'Squat with the bar racked on front delts, emphasizing quads and core.'),
(58, 'Goblet Squat', 'Squat holding a kettlebell or dumbbell at chest height.'),
(59, 'Leg Press', 'Machine press allowing heavy loading of the legs without spinal compression.'),
(60, 'Hack Squat', 'Machine squat that supports the back, isolating the quads.'),
(61, 'Walking Lunge', 'Dynamic lunge moving forward, hitting quads and glutes.'),
(62, 'Reverse Lunge', 'Stepping back into a lunge, safer for knees and targets glutes.'),
(63, 'Bulgarian Split Squat', 'Unilateral squat with the rear foot elevated on a bench.'),
(64, 'Step-Up', 'Stepping onto a box or bench, targeting glutes and quads.'),
(65, 'Leg Extension', 'Isolation machine exercise for the quadriceps.'),
(66, 'Sissy Squat', 'Bodyweight or weighted squat variation isolating the quads with a lean back.'),
(67, 'Pistol Squat', 'Advanced single-leg bodyweight squat requiring balance and strength.'),
(68, 'Hip Thrust', 'Barbell exercise focusing on peak glute contraction.'),
(69, 'Glute Bridge', 'Bodyweight or weighted bridge performed from the floor.'),
(70, 'Cable Pull Through', 'Hinging movement using a low cable targeting glutes and hams.'),
(71, 'Abductor Machine', 'Machine exercise pressing legs outward to target glutes/hips.'),
(72, 'Adductor Machine', 'Machine exercise squeezing legs inward to target inner thighs.'),

-- LEGS (HAMSTRINGS & CALVES)
(73, 'Romanian Deadlift (RDL)', 'Hinging movement keeping legs mostly straight to target hamstrings.'),
(74, 'Stiff Leg Deadlift', 'Similar to RDL but starting from the floor with minimal knee bend.'),
(75, 'Lying Leg Curl', 'Machine isolation exercise for hamstrings.'),
(76, 'Seated Leg Curl', 'Seated machine curl for hamstrings.'),
(77, 'Nordic Hamstring Curl', 'Bodyweight eccentric exercise for hamstrings (partner or anchor needed).'),
(78, 'Standing Calf Raise', 'Machine or weighted raise targeting the gastrocnemius.'),
(79, 'Seated Calf Raise', 'Seated machine raise targeting the soleus muscle.'),
(80, 'Donkey Calf Raise', 'Bent over calf raise, often with a partner or machine.'),
(81, 'Tibialis Raise', 'Raising toes upwards to target the front of the shin.'),

-- BICEPS
(82, 'Barbell Curl', 'Standard standing curl targeting the biceps brachii.'),
(83, 'Dumbbell Curl', 'Standing or seated curls allowing for wrist rotation.'),
(84, 'Hammer Curl', 'Neutral grip curl targeting the brachialis and forearms.'),
(85, 'Preacher Curl', 'Curl performed on a preacher bench to eliminate momentum.'),
(86, 'Concentration Curl', 'Seated single-arm curl resting elbow on thigh for isolation.'),
(87, 'Incline Dumbbell Curl', 'Seated incline curl that puts the biceps in a stretched position.'),
(88, 'EZ Bar Curl', 'Curl using an angled bar for better wrist comfort.'),
(89, 'Cable Bicep Curl', 'Curl using a low pulley for constant tension.'),
(90, 'Spider Curl', 'Curl performed lying face down on an incline bench.'),
(91, 'Zottman Curl', 'Curl up with palms up, rotate, and lower with palms down.'),
(92, 'Reverse Curl', 'Pronated grip curl targeting the forearms and brachialis.'),
(93, '21s', 'Partial rep scheme: 7 bottom half, 7 top half, 7 full reps.'),

-- TRICEPS
(94, 'Tricep Pushdown (Cable)', 'Pushing down a cable attachment targeting the lateral head.'),
(95, 'Tricep Rope Pushdown', 'Pushdown with a rope allowing for separation at the bottom.'),
(96, 'Skullcrusher', 'Lying tricep extension bringing the bar to the forehead.'),
(97, 'Overhead Tricep Extension', 'Extension performed behind the head (dumbbell or cable).'),
(98, 'Close Grip Bench Press', 'Bench press with narrow grip to emphasize triceps.'),
(99, 'Tricep Dips (Bench)', 'Bodyweight dips with hands on a bench and feet on floor.'),
(100, 'Tricep Kickback', 'Bent over extension using a dumbbell.'),
(101, 'JM Press', 'Hybrid between a close grip press and a skullcrusher.'),
(102, 'Single Arm Cable Extension', 'Unilateral extension using a cable setup.'),

-- CORE / ABS
(103, 'Plank', 'Isometric hold targeting the entire core.'),
(104, 'Side Plank', 'Isometric hold on one arm targeting obliques.'),
(105, 'Crunch', 'Standard flexion exercise for the abdominals.'),
(106, 'Sit-Up', 'Full range of motion flexion involving hip flexors.'),
(107, 'Hanging Leg Raise', 'Hanging from a bar and raising legs to target lower abs.'),
(108, 'Captain''s Chair Leg Raise', 'Leg raise supported by forearms on a station.'),
(109, 'Russian Twist', 'Seated twisting motion targeting obliques.'),
(110, 'Bicycle Crunch', 'Dynamic crunch bringing opposite elbow to knee.'),
(111, 'Ab Wheel Rollout', 'Rolling forward on a wheel, highly effective for core stability.'),
(112, 'Cable Crunch', 'Kneeling crunch pulling a rope attachment down.'),
(113, 'Woodchopper', 'Rotational cable movement simulating chopping wood.'),
(114, 'Dragon Flag', 'Advanced bodyweight core lever popularized by Bruce Lee.'),
(115, 'L-Sit', 'Holding legs horizontal while supporting bodyweight on hands.'),
(116, 'Vacuum', 'Isometric contraction of the transverse abdominis.'),
(117, 'Toes to Bar', 'Swinging or strict movement bringing toes to the pull-up bar.'),

-- CARDIO / RUNNING
(118, 'Treadmill Run', 'Running at a steady pace on a treadmill.'),
(119, 'Treadmill Incline Walk', 'Low impact cardio walking on a steep incline.'),
(120, 'Outdoor Run (5k)', 'Running a 5 kilometer distance.'),
(121, 'Sprints', 'Short bursts of maximum effort running.'),
(122, 'Elliptical Machine', 'Low impact cardio mimicking running motion.'),
(123, 'Stationary Bike', 'Cycling indoors for cardiovascular endurance.'),
(124, 'Recumbent Bike', 'Seated cycling with back support.'),
(125, 'Spinning Class', 'High intensity group cycling.'),
(126, 'Rowing Machine (Erg)', 'Full body cardiovascular workout using a rower.'),
(127, 'Stair Climber', 'Machine simulating climbing stairs continuously.'),
(128, 'Jump Rope', 'Skipping rope for conditioning and coordination.'),
(129, 'Double Unders', 'Jump rope variation passing rope twice per jump.'),
(130, 'Burpees', 'Full body metabolic conditioning movement.'),
(131, 'Mountain Climbers', 'Plank position running motion for core and cardio.'),
(132, 'Jumping Jacks', 'Classic calisthenic warm-up cardio.'),
(133, 'Box Jumps', 'Explosive jump onto a plyometric box.'),
(134, 'Battle Ropes', 'Upper body conditioning using heavy ropes.'),
(135, 'Assault Bike', 'High intensity fan bike utilizing arms and legs.'),
(136, 'Ski Erg', 'Vertical rowing motion simulating skiing.'),
(137, 'Swimming (Freestyle)', 'Laps using the freestyle stroke.'),
(138, 'Rucking', 'Walking or hiking with a weighted backpack.'),
(139, 'Fartlek Run', 'Running with unstructured intervals of speed and slow jogging.'),

-- CALISTHENICS / SKILLS
(140, 'Muscle-Up', 'Advanced pull-up transitioning into a dip above the bar.'),
(141, 'Human Flag', 'Holding the body horizontal sideways on a vertical pole.'),
(142, 'Front Lever', 'Holding body horizontal facing up while hanging from a bar.'),
(143, 'Back Lever', 'Holding body horizontal facing down while hanging from a bar.'),
(144, 'Handstand', 'Holding a vertical inverted position on hands.'),
(145, 'Handstand Push-Up', 'Vertical press performed from a handstand position.'),
(146, 'Planche', 'Holding body horizontal on floor supported only by hands.'),
(147, 'Skin the Cat', 'Rotating the body through the arms while hanging from rings/bar.'),
(148, 'Ring Dips', 'Dips performed on gymnastic rings requiring stability.'),

-- OLYMPIC LIFTING & CROSSFIT
(149, 'Snatch', 'Lifting the barbell from ground to overhead in one motion.'),
(150, 'Clean and Jerk', 'Two-part lift: ground to shoulders, then shoulders to overhead.'),
(151, 'Power Clean', 'Lifting bar to shoulders catching in a partial squat.'),
(152, 'Hang Clean', 'Clean initiated from a standing position (bar above knees).'),
(153, 'Thruster', 'Compound movement combining a front squat and overhead press.'),
(154, 'Wall Ball', 'Squatting and throwing a medicine ball to a target height.'),
(155, 'Kettlebell Swing', 'Hinging movement swinging a KB to eye level or overhead.'),
(156, 'Turkish Get-Up', 'Standing up from lying down while holding a weight overhead.'),
(157, 'Farmer''s Walk', 'Walking while carrying heavy weights in each hand.'),
(158, 'Yoke Walk', 'Carrying a heavy frame across the upper back.'),
(159, 'Sled Push', 'Pushing a weighted sled across turf.'),
(160, 'Sled Pull', 'Dragging a weighted sled backwards or forwards.'),

-- STRETCHING / MOBILITY
(161, 'Foam Rolling (Quads)', 'Self-myofascial release for the thigh muscles.'),
(162, 'Cat-Cow Stretch', 'Yoga flow mobilizing the spine.'),
(163, 'Pigeon Pose', 'Deep stretch for the glutes and hips.'),
(164, 'World''s Greatest Stretch', 'Lunge with rotation to mobilize hips and thoracic spine.'),
(165, 'Child''s Pose', 'Resting pose stretching the back and shoulders.');

COMMIT;